
package com.tutorial.webserviceClient.soap.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MathService", targetNamespace = "http://soap.webservice.tutorial.com/", wsdlLocation = "http://localhost:6060/math?wsdl")
public class MathService
    extends Service
{

    private final static URL MATHSERVICE_WSDL_LOCATION;
    private final static WebServiceException MATHSERVICE_EXCEPTION;
    private final static QName MATHSERVICE_QNAME = new QName("http://soap.webservice.tutorial.com/", "MathService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6060/math?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATHSERVICE_WSDL_LOCATION = url;
        MATHSERVICE_EXCEPTION = e;
    }

    public MathService() {
        super(__getWsdlLocation(), MATHSERVICE_QNAME);
    }

    public MathService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATHSERVICE_QNAME, features);
    }

    public MathService(URL wsdlLocation) {
        super(wsdlLocation, MATHSERVICE_QNAME);
    }

    public MathService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATHSERVICE_QNAME, features);
    }

    public MathService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Math
     */
    @WebEndpoint(name = "MathPort")
    public Math getMathPort() {
        return super.getPort(new QName("http://soap.webservice.tutorial.com/", "MathPort"), Math.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Math
     */
    @WebEndpoint(name = "MathPort")
    public Math getMathPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.webservice.tutorial.com/", "MathPort"), Math.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATHSERVICE_EXCEPTION!= null) {
            throw MATHSERVICE_EXCEPTION;
        }
        return MATHSERVICE_WSDL_LOCATION;
    }

}
